### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by reloonfire** [Enkosz/uri-parser#2]
PROLOG:
- [x] Funzionalità
     - [x] Schema zOs
     - [x] Implementare display/1
     - [x] Implementare display/2
     - [ ] Scrivere README
- [x] Migliorie
     - [ ]  Scrivere arità metodi
     - [ ]  Sistemare struttura codice
     - [ ] Wrap 80 colonne
- [x] Misc
     - [x] Encoding Spazi 
     - [x] Sistemare UserInfo per schemi speciali 
     - [x] Sistemare Ip con Atomi
     - [x] Gestione spazio nel path zOS
- [x] Testing
     - [x] Integration
     - [x] Secondo tipo di URI
     - [x] Schema
     - [x] UserInfo
     - [x] Host
     - [x] Ip
     - [x] Port
     - [x] Path
     - [x] Query
     - [x] Fragment
     - [x] Zos
     - [x] News
     - [x] Tel
     - [x] Fax
     - [x] Mailto
 
LISP:
- [ ] Funzionalità
     - [x] URI Tipo 1
     - [x] URI Tipo 2
     - [x] Scrivere IP
     - [x] Schema News
     - [x] Schema Mailto
     - [x] Schema zOS
     - [x] Schema Tel
     - [x] Implementare display/1
     - [ ] Implementare display/2
     - [ ] Scrivere README
- [ ] Migliorie
     - [ ]  Sistemare struttura codice
     - [ ] Wrap 80 colonne
- [x] Misc
     - [x] Encoding Spazi 
- [x] Testing
     - [x] Integration
     - [x] Secondo tipo di URI
     - [x] Schema
     - [x] UserInfo
     - [x] Host
     - [x] Ip
     - [x] Port
     - [x] Path
     - [x] Query
     - [x] Fragment
     - [x] Zos
     - [x] News
     - [x] Tel
     - [x] Fax
     - [x] Mailto
